# Generated by Django 4.2 on 2023-04-24 17:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('food', 'Food'), ('housing', 'Housing'), ('transportation', 'Transportation'), ('insurance', 'Insurance'), ('entertainment', 'Entertainment'), ('personal care', 'Personal Care'), ('healthcare', 'Healthcare'), ('loan', 'Loan'), ('taxes', 'Taxes'), ('gifts and donations', 'Gifts and Donations'), ('savings or investments', 'Savings or Investments'), ('kids', 'Kids'), ('other', 'Other')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
